### This notebook explains how Machine Learning can be applied to predict the species of Iris.
### This is a very famous dataset in the worl of machine learning and a base or new ML enthusiasts to start off with.
### We will be using the scikit-learn library and use KNN (K-Nearest-Neighbor) class and Logistic Regression class to perform ML over the Iris dataset
### The purpose of this notebook is to explain how the algorith functions and predicts the species of Iris.

- We are going to perform supervised learning using SciKitLearn library in Python 3.
- Goal is to predic the species using the measurements

In [1]:
from IPython.display import IFrame
IFrame('https://grape.ics.uci.edu/wiki/asterix/attachment/wiki/stats170ab-2018/iris.csv', width=300, height=200)

In [2]:
#importing the load_iris function sklearn module
from sklearn.datasets import load_iris

In [3]:
#saving the return object
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
# column heafers for the data
print(iris.feature_names)
#This is the actual dataset 
#col1 = sepal length, col2 = sepal width, col3 =  petal length, col4 = petal width
print(iris.data)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [6]:
#it represents what we are going to predict 0 = Setosa, 1 = Versicolor, 2 = virginica
print(iris.target)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [7]:
#storing features
# X & y are naming convention used to store the feature and response
#storing feature matrix in X
X = iris.data   
#storing response vector in y
y = iris.target
# both of them are already stored as nd arrays.

In [9]:
# checking the shape of both the objects
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [10]:
#Step1
# lets start using scikitlearn
#import the class you plan to use.
from sklearn.neighbors import KNeighborsClassifier

### Step2
### -lets 'intatiate' the 'estimater'
### -this is to tell the algorithm to look for the one nearet neighbor known as hyperparamenter.
### -all other parameters are default
### -its is waiting for the data at this point

In [42]:

knn = KNeighborsClassifier(n_neighbors=1)


In [43]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


### Step 3
### -Fit the model with data this is a training step whre the model learns the relationship between X & y
### - occurs in-place

In [44]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

### Step 4:
### - Lets predict a response for new observation 
### - new observations are also called as out-of-sample data
### - the model uses information from its training to predict the output

In [45]:
knn.predict([[ 3,5,4,2 ]])

array([2])

### returns a numpy array above the answer is 2 - versicolor
### can be used to predict multiple observations at once

In [46]:
#predicting multiple observations.
#create a list of observations.
new_obs = [[3,5,4,2], [5,4,3,2]]
knn.predict(new_obs)

array([2, 1])

### lets tune the model by changing the k value from 1 to 5 (model tuning)
- varying the argument that is passed to the model

In [47]:
# instantiate the model (using the value K=5)
knn = KNeighborsClassifier(n_neighbors= 5)

# fit the model with data
knn.fit(X, y)

# predict the response for new observations
knn.predict(new_obs)

array([1, 1])

# Lets use a Logistic regression model for classification using the 4 steps discussed above.

In [48]:
#1 import the module
from sklearn.linear_model import LogisticRegression
#2. Instantiate
lr = LogisticRegression()
#3 Fit the model
lr.fit(X,y)
#4 predict for out-of-sample data
lr.predict(new_obs)

array([2, 0])

### there is no definite way to prove which model is more accurate/correct because we are using an out-of-sample and we dont know its correct response values